import {useEffect,useRef,useState} from 'react'
import {api} from '../lib/api'
import type {Job} from '../types'
import {Icon} from './Icon'
export function ImportDialog({close,onDone}:{close:()=>void;onDone:()=>void}){
 const [job,setJob]=useState<Job|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false)
 const ref=useRef<HTMLDialogElement>(null)
 useEffect(()=>{ref.current?.showModal()},[])
 useEffect(()=>{if(!job||!['pending','processing'].includes(job.status))return;const timer=setInterval(()=>{api.job(job.id).then(j=>{setJob(j);if(j.status==='ready')onDone()}).catch(e=>setError(String(e)))},1200);return()=>clearInterval(timer)},[job,onDone])
 async function submit(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setBusy(true);setError('');const form=new FormData(e.currentTarget);const metadata={id:String(form.get('ticker')).toLowerCase()+'-'+form.get('accession'),ticker:String(form.get('ticker')).toUpperCase(),company:form.get('company'),cik:String(form.get('cik')).padStart(10,'0'),form:form.get('form'),fiscal_year:Number(form.get('fiscal_year')),period_end:form.get('period_end'),accession:form.get('accession'),source_url:form.get('source_url')};const data=new FormData();data.append('metadata',JSON.stringify(metadata));data.append('file',form.get('file') as File);try{setJob(await api.import(data))}catch(e){setError((e as Error).message)}finally{setBusy(false)}}
 return <dialog ref={ref} className="import-dialog" onCancel={close}><div className="panel-title"><span>Import a filing</span><button className="icon-button" onClick={close} aria-label="Close import"><Icon name="close"/></button></div><p className="subtle">Add a public SEC inline-XBRL HTML filing to your local library. Its text and financial facts will be indexed together.</p>
 {job?<div className="import-progress"><Icon name={job.status==='ready'?'check':'clock'} size={32}/><h3>{job.status==='ready'?'Filing ready':job.status==='failed'?'Import needs attention':'Importing and indexing'}</h3><p>{job.error||'Your import is saved locally and can resume after an API restart.'}</p>{job.status==='failed'&&<button className="primary" onClick={()=>api.retry(job.id).then(setJob)}>Retry import</button>}<button className="secondary" onClick={close}>{job.status==='ready'?'Back to library':'Close'}</button></div>:<form onSubmit={submit} className="import-form"><div className="field-grid"><label>Ticker<input required name="ticker" placeholder="AAPL" maxLength={10}/></label><label>Company<input required name="company" placeholder="Apple Inc."/></label><label>CIK<input required name="cik" placeholder="0000320193" pattern="[0-9]{1,10}"/></label><label>Form<select name="form"><option>10-K</option><option>10-K/A</option><option>10-Q</option><option>10-Q/A</option></select></label><label>Fiscal year<input required name="fiscal_year" type="number" min="1990" max="2100" placeholder="Fiscal year"/></label><label>Period end<input required name="period_end" type="date"/></label></div><label>Accession number<input required name="accession" placeholder="0000320193-24-000123" pattern="[0-9]{10}-[0-9]{2}-[0-9]{6}"/></label><label>SEC archive URL<input required name="source_url" type="url" placeholder="https://www.sec.gov/Archives/edgar/data/…"/></label><label>Filing HTML<input required name="file" type="file" accept=".html,.htm"/></label>{error&&<div role="alert" className="notice error">{error}</div>}<button disabled={busy} className="primary" type="submit">{busy?'Saving import…':'Import and index'}<Icon name="arrow"/></button></form>}
 </dialog>
}
