export interface Filing { id:string; ticker:string; company:string; cik:string; form:string; fiscal_year:number; period_end:string; accession:string; source_url:string; chunk_count:number; fact_count:number; checksum:string }
export interface Corpus {filings:Filing[]; sections:string[]; scope:string}
export interface Health {status:string; filings:number; chunks:number; indexed:number; embedding_model:string; ollama_enabled:boolean}
export interface Source {id:string; type:'fact'|'passage'; ticker:string; company:string; filing_id:string; form:string; accession:string; section:string; text:string; source_url:string; period_start?:string|null; period_end:string; concept?:string; value?:string; unit?:string; decimals?:string; context_id?:string; bm25_score?:number; dense_score?:number; rrf_score?:number; rerank_score?:number|null; ordinal?:number; kind?:string}
export interface Claim {text:string; quote?:string; source_ids:string[]; kind:string}
export interface Calculation {label:string; ticker:string; value:string; display_value:string; formula:string; operands:string[]; fiscal_year:number; period_start:string; period_end:string}
export interface QueryResponse {id:string; question:string; status:'supported'|'partial'|'insufficient_evidence'; claims:Claim[]; sources:Source[]; calculations:Calculation[]; issues:string[]; answer_mode:string; citation_validation:string; trace:{retrieval:string; reranked:boolean; embedding_model:string|null; candidate_sources:number; cited_sources:number; elapsed_ms:number}}
export interface QueryRequest {question:string;tickers:string[];fiscal_year:number;section?:string;retrieval:'hybrid'|'bm25'|'dense';answer_mode:'extractive'|'ollama';top_k:number;rerank:boolean}
export interface Job {id:string;status:string;result:unknown;error:string|null}
export interface EvalMetrics {recall_at_5:number;mrr_at_5:number;cases:number;latency_median_ms:number;latency_p95_ms:number;hit_count:number;failures:{id:string;question:string;retrieved:string[]}[]}
export interface Evaluation {corpus:{filings:number;chunks:number;sha256:string};retrieval:Record<string,EvalMetrics>;financial:{passed:number;total:number;failures:unknown[]};abstention:{passed:number;total:number;failures:unknown[]};citation:{passed:number;total:number};scope:string;models:Record<string,string>;cases:unknown[]}
