import {test,expect} from '@playwright/test'

test('light workspace loads without contacting external services',async({page})=>{
 const external:string[]=[],errors:string[]=[]
 page.on('request',req=>{if(!req.url().startsWith('http://127.0.0.1:8000'))external.push(req.url())})
 page.on('pageerror',e=>errors.push(e.message))
 await page.goto('/')
 await expect(page.getByText('Corpus ready',{exact:true})).toBeVisible()
 await expect(page.getByRole('heading',{name:'Every answer begins with evidence.'})).toBeVisible()
 expect(await page.locator('.sidebar').evaluate(e=>getComputedStyle(e).backgroundColor)).toBe('rgb(238, 241, 232)')
 expect(external).toEqual([]);expect(errors).toEqual([])
})

test('comparison exposes independent operands, periods and original source',async({page})=>{
 await page.goto('/')
 await page.getByRole('button',{name:/Compare operating margins/}).click()
 await expect(page.getByRole('tab',{name:'Answer',exact:true})).toBeVisible()
 await expect(page.getByText('31.51%',{exact:true})).toBeVisible()
 await expect(page.getByText('44.64%',{exact:true})).toBeVisible()
 await expect(page.getByText(/different fiscal year ends/)).toBeVisible()
 await page.getByRole('tab',{name:/Calculations/}).click()
 await expect(page.getByText('Inspect the calculation.')).toBeVisible()
 await page.locator('.operand-list button').first().click()
 await expect(page.getByText('Source inspector',{exact:true})).toBeVisible()
 await expect(page.getByText('0000320193-24-000123',{exact:true})).toBeVisible()
 await expect(page.getByRole('link',{name:/Open original SEC filing/})).toHaveAttribute('href',/^https:\/\/www.sec.gov\/Archives\//)
})

test('unsupported questions decline and history survives reload',async({page})=>{
 await page.goto('/')
 await page.getByRole('button',{name:/Ask beyond the available evidence/}).click()
 await expect(page.getByText('The filings don’t support this answer.')).toBeVisible()
 await expect(page.locator('.claims')).toBeEmpty()
 await page.reload()
 await page.locator('.history-list button').filter({hasText:'Predict Apple stock price'}).first().click()
 await expect(page.getByText('The filings don’t support this answer.')).toBeVisible()
})

test('source extracts retain exact citations and retrieval details',async({page})=>{
 await page.goto('/')
 await page.getByRole('button',{name:/Where is Apple’s supply chain exposed/}).click()
 await expect(page.getByRole('tab',{name:'Answer',exact:true})).toBeVisible()
 const claims=await page.locator('.claim p').allTextContents()
 expect(claims.length).toBeGreaterThan(0)
 await page.locator('.citation').first().click()
 await expect(page.getByText('Source inspector',{exact:true})).toBeVisible()
 await page.getByRole('tab',{name:'Retrieval details'}).click()
 await expect(page.getByText('A visible research trail.')).toBeVisible()
 await expect(page.getByText(/not calibrated answer-confidence/)).toBeVisible()
})

test('recorded evaluation and library are usable',async({page})=>{
 await page.goto('/')
 await page.getByRole('button',{name:/Filing library/}).click()
 await expect(page.getByRole('heading',{name:'A library you can inspect.'})).toBeVisible()
 await expect(page.locator('.filing-card')).toHaveCount(3)
 await page.getByRole('button',{name:'Evaluation',exact:true}).click()
 await expect(page.getByRole('heading',{name:'Evidence for the evidence.'})).toBeVisible()
 await expect(page.getByText('Hybrid + cross-encoder',{exact:false})).toBeVisible()
 await page.getByText('Inspect retrieval misses',{exact:true}).click()
 await expect(page.locator('.failure-details')).toHaveAttribute('open','')
})

test('mobile has scope selection and no horizontal overflow',async({page})=>{
 await page.setViewportSize({width:390,height:844})
 await page.goto('/')
 await expect(page.getByText('Corpus ready',{exact:true})).toBeVisible()
 await expect(page.getByLabel('Issuer scope')).toBeVisible()
 await page.getByLabel('Issuer scope').selectOption('MSFT')
 await page.getByLabel('Research question',{exact:true}).fill('Microsoft revenue')
 await page.getByRole('button',{name:'Research question submit'}).click()
 await expect(page.getByRole('tab',{name:'Answer',exact:true})).toBeVisible()
 expect(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth)).toBe(true)
})

test('real filing reimport is durable and does not duplicate its accession',async({page})=>{
 await page.goto('/')
 await page.getByRole('button',{name:/Filing library/}).click()
 await page.getByRole('button',{name:'Import a filing',exact:true}).click()
 await page.getByLabel('Ticker',{exact:true}).fill('AAPL')
 await page.getByLabel('Company',{exact:true}).fill('Apple Inc.')
 await page.getByLabel('CIK',{exact:true}).fill('0000320193')
 await page.getByLabel('Fiscal year',{exact:true}).fill('2024')
 await page.getByLabel('Period end',{exact:true}).fill('2024-09-28')
 await page.getByLabel('Accession number',{exact:true}).fill('0000320193-24-000123')
 await page.getByLabel('SEC archive URL',{exact:true}).fill('https://www.sec.gov/Archives/edgar/data/320193/000032019324000123/aapl-20240928.htm')
 await page.getByLabel('Filing HTML',{exact:true}).setInputFiles('../data/filings/aapl-2024.html')
 await page.getByRole('button',{name:'Import and index'}).click()
 await expect(page.getByRole('heading',{name:'Filing ready',exact:true})).toBeVisible()
 await page.getByRole('button',{name:'Back to library'}).click()
 await expect(page.locator('.filing-card')).toHaveCount(3)
})

test('failed requests never display a previous answer as the new result',async({page})=>{
 await page.goto('/')
 await page.getByRole('button',{name:/Compare operating margins/}).click()
 await expect(page.getByText('31.51%',{exact:true})).toBeVisible()
 await page.route('**/api/query',route=>route.fulfill({status:503,contentType:'application/json',body:JSON.stringify({detail:'The local index is unavailable.'})}))
 await page.getByLabel('Research question',{exact:true}).fill('Apple revenue')
 await page.getByRole('button',{name:'Research question submit'}).click()
 await expect(page.getByRole('alert')).toContainText('The local index is unavailable.')
 await expect(page.locator('.claims')).toHaveCount(0)
})
